solved problem 3.3 from the site stepik to move the robot
Yurii666/Education pull request #4
Opened 2021-11-05 15:06 UTC by Yurii666

2021-11-07 17:39 UTC, Loienko requested changes

2021-11-07 17:39 UTC, Loienko commented on src/Stepic/RobotDemo.java
> +             int x;
I don't understand what does it mean - 'x' and what should it do? 
What is the value of this variable?
This is the coordinateX or something else?

2021-11-07 17:39 UTC, Loienko commented on src/Stepic/RobotDemo.java
> +              this.y = y;
the same as above

2021-11-07 17:39 UTC, Loienko commented on src/Stepic/RobotDemo.java
> +             else if (dir == Direction.RIGHT) {dir = Direction.UP;}
Use brackets anywhere, anytime

2021-11-07 17:39 UTC, Loienko commented on src/Stepic/RobotDemo.java
> +             if (dir == Direction.UP)    {y++;}
the same as above

2021-11-07 23:26 UTC, Yurii666 commented on src/Stepic/RobotDemo.java
> +             else if (dir == Direction.RIGHT) {dir = Direction.UP;}
is it sarcasm, or a message to action?

2021-11-07 23:27 UTC, Yurii666 commented on src/Stepic/RobotDemo.java
> +             if (dir == Direction.UP)    {y++;}
они же здесь и так есть

2021-11-09 07:11 UTC, Loienko commented on src/Stepic/RobotDemo.java
> +             else if (dir == Direction.RIGHT) {dir = Direction.UP;}
This is a message to action

2021-11-09 07:13 UTC, Loienko approved these changes

2021-11-09 20:04 UTC, merged